DROP TABLE IF EXISTS rides CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT users_login_not_blank CHECK (btrim(login) <> ''),
    CONSTRAINT users_password_not_blank CHECK (btrim(password) <> ''),
    CONSTRAINT users_full_name_not_blank CHECK (btrim(full_name) <> '')
);

CREATE TABLE drivers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    car_model VARCHAR(100) NOT NULL,
    car_number VARCHAR(30) NOT NULL UNIQUE,
    license_number VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'online',
    CONSTRAINT fk_drivers_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT drivers_car_model_not_blank CHECK (btrim(car_model) <> ''),
    CONSTRAINT drivers_car_number_not_blank CHECK (btrim(car_number) <> ''),
    CONSTRAINT drivers_license_number_not_blank CHECK (btrim(license_number) <> ''),
    CONSTRAINT drivers_status_valid CHECK (status IN ('online', 'busy', 'offline'))
);

CREATE TABLE rides (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id INTEGER NOT NULL,
    driver_id INTEGER NULL,
    pickup_address VARCHAR(255) NOT NULL,
    destination_address VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'searching',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMP NULL,
    CONSTRAINT fk_rides_passenger
        FOREIGN KEY (passenger_id) REFERENCES users(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_rides_driver
        FOREIGN KEY (driver_id) REFERENCES drivers(id)
        ON DELETE RESTRICT,
    CONSTRAINT rides_pickup_not_blank CHECK (btrim(pickup_address) <> ''),
    CONSTRAINT rides_destination_not_blank CHECK (btrim(destination_address) <> ''),
    CONSTRAINT rides_status_valid CHECK (status IN ('searching', 'accepted', 'completed', 'cancelled'))
);

CREATE INDEX idx_users_full_name_trgm
    ON users USING GIN (lower(full_name) gin_trgm_ops);

CREATE INDEX idx_drivers_status ON drivers(status);
CREATE INDEX idx_drivers_user_id ON drivers(user_id);

CREATE INDEX idx_rides_passenger_id ON rides(passenger_id);
CREATE INDEX idx_rides_driver_id ON rides(driver_id);
CREATE INDEX idx_rides_status ON rides(status);
CREATE INDEX idx_rides_passenger_status ON rides(passenger_id, status);
CREATE INDEX idx_rides_created_at ON rides(created_at DESC);
