worker-threads: 2
worker-fs-threads: 2
worker-db-threads: 2
logger-level: debug
is-testing: true
server-port: 8080
dbconnection: postgresql://taxi:taxi123@postgres:5432/taxi
mongo-connection: mongodb://mongo:27017/taxi_mongo_db
